### ISSUE TITLE
Accessing Shadow DOM

### ISSUE THREAD

**Issue by ppeou** [schollz/puppeteer#1]
Hi,

Is there a way I can access Shadow Dom such as Polymer Element using Pupeteer?

Thanks,

**Comment by schollz** [comment]
Sorry, I can't help. I don't maintain this, it's just a personal fork of https://github.com/GoogleChrome/puppeteer. They can help you there!

**Comment by ppeou** [comment]
Shcoll, 
thanks for quick reply. :)
